variables:
  BUILD_DIR: /home/gitlab-runner/builds/$CI_RUNNER_SHORT_TOKEN/0/bkbm-addon/kb-tab-for-woocommerce
  DEPLOY_DIR: bkbm/wp-content/plugins/kb-tab-for-woocommerce

stages:
  - build
  - staging
  - production
  - cleanup # Added cleanup stage

before_script:
  - sudo apt-get update
  - sudo apt-get install -y lftp curl npm php-cli unzip
  - mkdir -p "$HOME/bin"
  - curl -sS https://getcomposer.org/installer | php -- --install-dir="$HOME/bin" --filename=composer
  - export PATH="$HOME/bin:$PATH"
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"

build:
  stage: build
  image: node:lts
  tags: [ci, devops]
  only: [staging, production]
  script:
    - composer install --no-dev --optimize-autoloader
    - nvm install
    - nvm use
    - npm install
    - npm run build
  artifacts:
    paths:
      - $BUILD_DIR/assets
      - $BUILD_DIR/vendor

staging:
  stage: staging
  dependencies:
    - build
  only: [staging]
  tags: [ci, devops]
  script:
    - pwd
    - echo "Updating plugin files.."
    - lftp -e "set ssl:verify-certificate no; open $FTP_SHOST; user $FTP_SUSERNAME $FTP_SPASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete $BUILD_DIR /wpplugins/$DEPLOY_DIR; bye"

production:
  stage: production
  dependencies:
    - build
  only: [production]
  tags: [ci, devops]
  script:
    - pwd
    - echo "Updating plugin files.."
    - lftp -e "set ssl:verify-certificate no; open $FTP_HOST; user $FTP_PUSERNAME $FTP_PPASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete $BUILD_DIR /wpplugin/$DEPLOY_DIR; bye"

# Cleanup job added to remove unnecessary files after deployment
cleanup:
  stage: cleanup # Stage after production
  only: [staging, production]
  tags: [ci, devops]
  script:
    - echo "Cleaning up temporary files and artifacts..."
    - rm -rf $BUILD_DIR/assets # Adjust this to your specific cleanup needs
    - rm -rf $BUILD_DIR/vendor # Adjust this to your specific cleanup needs
    - echo "Cleanup complete."
