variables:
  BUILD_DIR: /home/gitlab-runner/builds/$CI_RUNNER_SHORT_TOKEN/0/plugin-addons/kb-tab-for-woocommerce # Adjusted
  PLUGIN_DIR: bkbm/wp-content/plugins/kb-tab-for-woocommerce/ # Adjusted
  SDEPLOY_DIR: /home/$SHOST_ID/public_html/bwl_staging/wpplugins/$PLUGIN_DIR # Adjusted
  PDEPLOY_DIR: /home/$PHOST_ID/public_html/public_html/projects/wpplugin/$PLUGIN_DIR # Adjusted

stages:
  - build
  - staging
  - production
  - cleanup

before_script:
  - echo "👨🏻‍💻 Getting ready!!"
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=$HOME/bin --filename=composer
  - export PATH="$HOME/bin:$PATH"
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"

build:
  stage: build
  image: node:lts
  tags: [ci, devops]
  only: [staging, production]
  script:
    - echo "⚙️ Building the app."
    - composer install --no-dev --optimize-autoloader
    - nvm use
    - npm install
    - npm run build
    - npm run make-pot
  artifacts:
    paths:
      - $BUILD_DIR/assets
      - $BUILD_DIR/vendor

staging:
  stage: staging
  dependencies:
    - build
  only: [staging]
  tags: [ci, devops]
  script:
    - echo "🚀 Deploying to STAGING."
    - rsync -avz --delete --exclude-from='.rsync-exclude' -e "ssh -p ${SSH_PORT:-65002}" $BUILD_DIR/ $SSH_SUSERNAME@$SSH_SHOST:$SDEPLOY_DIR

production:
  stage: production
  dependencies:
    - build
  only: [production]
  tags: [ci, devops]
  script:
    - echo "🚀 Deploying to PRODUCTION."
    - rsync -avz --delete --exclude-from='.rsync-exclude' -e "ssh -p ${SSH_PORT:-65002}" $BUILD_DIR/ $SSH_PUSERNAME@$SSH_PHOST:$PDEPLOY_DIR

cleanup:
  stage: cleanup
  only: [staging, production]
  tags: [ci, devops]
  script:
    - echo "🧹Cleaning up."
    - rm -rf $BUILD_DIR
